skip_docs

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a built version to the Google Play Beta track"
  lane :deploy do |options|
    if options[:aab]
	  upload_to_play_store(track: 'beta', aab: options[:aab], validate_only: true)
    else
      UI.user_error!("Cannot deploy because no aab given - please specify :aab")
    end
  end
end
