openapi: 3.0.0
info:
  title: Untis Mobile API
  description: |
    A reverse-engineered documentation of the Untis Mobile REST API.
    
    Keep in mind that this API seems to be a new JSON REST API.
    The older JSONRPC-API is still being used for most content (like user info and timetable).
  version: 1.0.0

servers:
  - url: https://{host}.webuntis.com/WebUntis/api/rest/view/v1
    variables:
      host:
        enum:
          - achilles
          - antiope
          - aoide
          - arche
          - asopo
          - cissa
          - erato
          - euterpe
          - hektor
          - hepta
          - herakles
          - hypate
          - kalliope
          - kephiso
          - klio
          - melete
          - melpomene
          - mese
          - nete
          - niobe
          - terpsichore
          - thalia
          - tipo
          - tritone
          - urania
        default: hektor

tags:
  - name: messages
    description: Send and receive messages
  - name: user
    description: Get information about the user

security:
  - bearerAuth: []

paths:
  /messages:
    get:
      summary: Get a list of received messages
      tags:
        - messages
      security:
        - bearerAuth: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessagesResponse'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /messages/sent:
    get:
      summary: Get a list of sent messages
      tags:
        - messages
      security:
        - bearerAuth: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessagesSentResponse'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /messages/drafts:
    get:
      summary: Get a list of message drafts
      tags:
        - messages
      security:
        - bearerAuth: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessagesDraftsResponse'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /messages/status:
    get:
      summary: Get a status summary for messages
      tags:
        - messages
      security:
        - bearerAuth: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessagesStatusResponse'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /messages/permissions:
    get:
      summary: Get message-related permissions
      tags:
        - messages
      security:
        - bearerAuth: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessagesPermissionsResponse'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /mobile/data:
    get:
      summary: Get user data
      tags:
        - user
      security:
        - bearerAuth: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MobileDataResponse'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /home:
    get:
      summary: Get information about the user home page
      tags:
        - user
      security:
        - bearerAuth: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HomeResponse'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        errorCode:
          type: string
          enum:
            - INTERNAL_ERROR
            # Other values unknown
        requestId:
          type: string
          format: uuid
        traceId:
          type: string
        errorMessage:
          type: string

    MessagesResponse:
      type: object
      properties:
        incomingMessages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
        readConfirmationMessages:
          type: array
          items:
            $ref: '#/components/schemas/Message'

    MessagesSentResponse:
      type: object
      properties:
        sentMessages:
          type: array
          items:
            $ref: '#/components/schemas/Message'

    MessagesDraftsResponse:
      type: object
      properties:
        draftMessages:
          type: array
          items:
            $ref: '#/components/schemas/Message'

    MessagesStatusResponse:
      type: object
      properties:
        unreadMessagesCount:
          type: number

    MessagesPermissionsResponse:
      type: object
      properties:
        recipientOptions:
          type: string
          enum:
            - TEACHER
            # Other values unknown
        allowRequestReadConfirmation:
          type: boolean
        recipientSearchMaxResult:
          type: number
          example: 100
        showDraftsTab:
          type: boolean
        showSentTab:
          type: boolean
        canForbidReplies:
          type: boolean
        maxFileSize:
          type: number
          example: 7000000
        maxFileCount:
          type: number
          example: 5

    MobileDataResponse:
      type: object
      properties:
        schoolYear:
          $ref: '#/components/schemas/SchoolYear'
        tenant:
          $ref: '#/components/schemas/Tenant'
        user:
          $ref: '#/components/schemas/User'

    HomeResponse:
      type: object
      properties:
        schoolname:
          type: string
        sections:
          type: array
          items:
            $ref: '#/components/schemas/HomeSection'
        integrationsSection:
          type: array
          items:
            $ref: '#/components/schemas/HomeIntegrationSection'

    Message:
      description: |
        Model can be found in Untis Mobile source:
        com/untis/mobile/messages/data/model
      type: object
      properties:
        allowMessageDeletion:
          type: boolean
        attachments:
          type: array
          items:
            $ref: '#/components/schemas/MessageAttachment'
        content:
          type: string
        contentPreview:
          type: string
        hasAttachments:
          type: boolean
        id:
          type: string
        isMessageRead:
          type: boolean
        isReply:
          type: boolean
        isReplyAllowed:
          type: boolean
        isReportMessage:
          type: boolean
        isRevoked:
          type: boolean
        blobAttachment:
          $ref: '#/components/schemas/MessageAttachment'
        requestConfirmation:
          $ref: '#/components/schemas/MessageRequestConfirmation'
        storageAttachments:
          type: array
          items:
            $ref: '#/components/schemas/MessageAttachment'
        numberOfRecipients:
          type: integer
        recipientGroups:
          type: array
          items:
            $ref: '#/components/schemas/Recipient'
        recipientPersons:
          type: array
          items:
            $ref: '#/components/schemas/Recipient'
        recipients:
          type: array
          items:
            $ref: '#/components/schemas/Recipient'
        replyHistory:
          type: array
          items:
            $ref: '#/components/schemas/Message'
        requestConfirmationStatus:
          $ref: '#/components/schemas/RequestConfirmationStatus'
        sender:
          $ref: '#/components/schemas/Sender'
        sentDateTime:
          type: string
          format: date-time
        subject:
          type: string

    MessageAttachment:
      type: object
      description: TODO

    MessageRequestConfirmation:
      type: object
      description: TODO

    RequestConfirmationStatus:
      type: object
      description: TODO

    Sender:
      type: object
      description: TODO

    Recipient:
      type: object
      description: TODO

    DateRange:
      type: object
      properties:
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time

    SchoolYear:
      type: object
      properties:
        dateRange:
          $ref: '#/components/schemas/DateRange'
        id:
          type: number
        name:
          type: string
          example: '2023/2024'

    Tenant:
      type: object
      properties:
        id:
          type: string
        displayName:
          type: string
        wuVersion:
          type: string

    Person:
      type: object
      properties:
        id:
          type: number
        displayName:
          type: string
        imageUrl:
          type: string
          format: uri

    User:
      type: object
      properties:
        id:
          type: number
        username:
          type: string
        person:
          $ref: '#/components/schemas/Person'
        referencedStudents:
          type: array
          # Item type unknown
          items:
            type: object
        locale:
          type: string
        departmentId:
          type: number
        role:
          type: string
        permissions:
          type: array
          items:
            type: string

    HomeSection:
      type: object
      properties:
        cells:
          type: array
          items:
            $ref: '#/components/schemas/HomeSectionCell'

    HomeSectionCell:
      type: object
      properties:
        badge:
          $ref: '#/components/schemas/HomeSectionCellBadge'
        type:
          type: string
          enum:
            - MY_EVENTS
            - CLASS_TEACHER
            - PARENTS_DAYS
            - CONTACT_HOURS
            - STUDENT_ABSENCES
            - TEACHER_ABSENCES
            - SUBSTITUTION_REQUESTS
            - STUDENT_ABSENCES_ADMINISTRATION
            - n/a

    HomeSectionCellBadge:
      type: object
      nullable: true
      properties:
        count:
          type: number

    HomeIntegrationSection:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        url:
          type: string
          format: uri
        iconName:
          type: string
        type:
          type: string
          enum:
            - APP
            - WEB
        appId:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
