openapi: 3.0.0
info:
  title: Untis Mobile API
  description: |
    A reverse-engineered documentation of the Untis Mobile REST API.
    
    Keep in mind that this API seems to be a new JSON REST API.
    The older JSONRPC-API is still being used for most content (like user info and timetable).
  version: 1.0.0

servers:
  - url: https://{host}.webuntis.com/WebUntis/api/mobile/v2
    variables:
      host:
        enum:
          - achilles
          - antiope
          - aoide
          - arche
          - asopo
          - cissa
          - erato
          - euterpe
          - hektor
          - hepta
          - herakles
          - hypate
          - kalliope
          - kephiso
          - klio
          - melete
          - melpomene
          - mese
          - nete
          - niobe
          - terpsichore
          - thalia
          - tipo
          - tritone
          - urania
        default: hektor

tags:
  - name: authentication
    description: Authentication operations

security:
  - bearerAuth: []

paths:
  /{schoolName}/authentication:
    post:
      summary: Get a list of received messages
      tags:
        - authentication
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: schoolName
          required: true
          schema:
            type: string
      requestBody:
        description: Login credentials
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthenticationRequest"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponse'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Jwt:
      type: string
      format: jwt
      description: JWT for authentication in subsequent requests
      example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c

    ErrorResponse:
      anyOf:
        - type: object
          properties:
            type:
              type: string
              enum:
                - BAD_CREDENTIALS
                # Other values unknown
        - type: object
          properties:
            errorCode:
              type: string
              enum:
                - INTERNAL_ERROR
                # Other values unknown
            requestId:
              type: string
              format: uuid
            traceId:
              type: string
            errorMessage:
              type: string

    AuthenticationRequest:
      type: object
      properties:
        username:
          type: string
          description: Username for authentication
        password:
          type: string
          description: Password for authentication
      required:
        - username
        - password

    AuthenticationResponse:
      type: object
      properties:
        jwt:
          $ref: '#/components/schemas/Jwt'
        isEmailUpdateRequired:
          type: boolean
          description: |
            Indicates if the user should be prompted to update their email address.
            Use `PUT /profile/user-contact-data` from the rest-view-v1 API to update the email address.
        isPasswordChangeRequired:
          type: boolean
          description: |
            Indicates if the user should be prompted to change their password.
            Exact behavior for this flag is not known.

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
