name: Build App

on:
  push:
    branches-ignore:
      'fdroid-*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        # Only write to the cache for builds on the 'main' and 'develop' branches. (Default is 'main' only.)
        # Builds on other branches will only read existing entries from the cache.
        cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}

    - name: Prepare signing config
      run: |
        if [[ ! -v KEYSTORE_ENCODED ]]; then exit 0; fi
        echo $KEYSTORE_ENCODED | base64 --decode >> app/BetterUntis.jks
        echo 'export KEYSTORE_PASSWORD=$(echo "$KEYSTORE_PASSWORD_ENCODED" | base64 --decode)' >> $BASH_ENV
        echo 'export KEY_DEBUG_PASSWORD=$(echo "$KEY_DEBUG_PASSWORD_ENCODED" | base64 --decode)' >> $BASH_ENV
        echo 'export KEY_RELEASE_PASSWORD=$(echo "$KEY_RELEASE_PASSWORD_ENCODED" | base64 --decode)' >> $BASH_ENV

    - name: Build with Gradle
      run: ./gradlew assemble bundle

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: outputs
        path: 'app/build/outputs'
