name: Deploy App

on:
  push:
    #tags:
      #- "[0-9]+.[0-9]+.[0-9]+"
      #- "[0-9]+.[0-9]+.[0-9]+-[a-zA-Z0-9]+"

permissions:
  contents: write

jobs:
  build:
    name: Build release APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
  
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Prepare signing config
        run: |
          if [[ ! -v KEYSTORE_ENCODED ]]; then exit 0; fi
          echo $KEYSTORE_ENCODED | base64 --decode >> app/BetterUntis.jks
          echo 'export KEYSTORE_PASSWORD=$(echo "$KEYSTORE_PASSWORD_ENCODED" | base64 --decode)' >> $BASH_ENV
          echo 'export KEY_DEBUG_PASSWORD=$(echo "$KEY_DEBUG_PASSWORD_ENCODED" | base64 --decode)' >> $BASH_ENV
          echo 'export KEY_RELEASE_PASSWORD=$(echo "$KEY_RELEASE_PASSWORD_ENCODED" | base64 --decode)' >> $BASH_ENV

      - name: Assemble release
        run: ./gradlew assembleGmsRelease bundleGmsRelease

      - name: Upload release files
        uses: actions/upload-artifact@v4
        with:
          name: betteruntis-release
          path: app/build/outputs

  github:
    name: Create Release on GitHub
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: betteruntis-release
          path: app/build/outputs
          
      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: 5.0.0-beta01 #${{ github.ref_name }}
        run: |
          gh release create "$TAG" \
              --prerelease \
              --title "BetterUntis $TAG" \
              --notes-file "./fastlane/metadata/android/en-US/changelogs/$TAG.txt" \
              "./app/build/outputs/apk/gms/release/app-gms-release.apk#BetterUntis $TAG.apk"
